import { Outfit } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"

const outfit = Outfit({
  subsets: ["latin"],
})

export const metadata = {
  title: "Botsync",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`$${outfit.className} scrollbar-hidden antialiased`}>
        <div className="flex">
          <Sidebar />
          <div className="w-full ml-0 md:ml-54">
            <Navbar />
            <div className="m-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
